project:
  type: website

website:
  title: ""
  navbar:
    background: light
    search: true
    right:
      - href: index.qmd
        text: About me
      - icon: rss
        href: index.xml

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Chakra+Petch" type="text/css"/>
    link-citations: yes
    mainfont: Chakra Petch

execute:
  freeze: auto



